Vagrant.require_version ">= 2.4.1"
image      =  "generic/centos8"
cpus       =  "2"
memory     =  "6000"
gui        =  false
count      =  2

Vagrant.configure("2") do |multi|
  multi.vm.provision "shell", path: "generic.sh"
  
  (1..count).each do |i|
    private_ip = "192.168.56.2#{i}"
    host_name  =  "centos#{i}.vbox"
    guest_name =  "centos#{i}"

    multi.vm.define "centos_#{i}" do | multi_node |
      multi_node.vm.box      = image
      multi_node.vm.hostname = host_name
      multi_node.vm.network "private_network", ip: private_ip, hostname: true

      multi_node.vm.provider "virtualbox" do | node |
        node.name    = guest_name
        node.gui     = gui
        node.cpus    = cpus
        node.memory  = memory
      end
    end
  end  
end
