Vagrant.require_version ">= 2.4.3"
image      =  "generic/centos9s"
cpus       =  "2"
memory     =  "4000"
gui        =  false
count      =  1

Vagrant.configure("2") do |multi|
  multi.vm.provision "shell", path: "generic.sh"

  (1..count).each do |i|
    host_name  =  "kube#{i}.vbox"
    guest_name =  "kube#{i}"

    multi.vm.define "kube_#{i}" do | multi_node |
      multi_node.vm.box         = image
      multi_node.vm.hostname    = host_name
      multi_node.vm.network "public_network"

      multi_node.vm.provider "virtualbox" do | node |
        node.name    = guest_name
        node.gui     = gui
        node.cpus    = cpus
        node.memory  = memory
      end
    end
  end  
end
